### ISSUE TITLE
Error opening params file

### ISSUE THREAD

**Issue by AlexGaithuma** [gear-genomics/dicey#1]
I have an error when I run dicey..
my commands are:

    script="/media/bioadmin/24e12c01-7941-49f5-9647-eeebabd15082/packages/dicey/scripts/json2txt.py"
    config="/media/bioadmin/24e12c01-7941-49f5-9647-eeebabd15082/packages/dicey/src/primer3_config"

    echo -e ">566F\CAGCAGCCGCGGTAATTCC\n>1200R\nCCCGTGTTGAGTCAAATTAAGC" > primers.fa

    dicey search -c 45 -l 1000 -g ../18S_All.fasta primers.fa -i $config | python $script
I get the error:

    Error opening params file
    Error opening params file
    Segmentation fault (core dumped)

**Comment by tobiasrausch** [comment]
Have you installed dicey using bioconda? The primer3 config directory is only included in the source code. Please also check that the config files are really present in that directory, i.e.:

`ls $config/tetraloop.dh`

**Comment by AlexGaithuma** [comment]
I compiled from the source and tetraloop.dh file is present.

**Comment by tobiasrausch** [comment]
Thanks. Sorry I haven't seen this earlier but you use a custom reference (../18S_All.fasta primers.fa). You need to index this reference first as described in the [README](https://github.com/gear-genomics/dicey) because dicey is designed to work across entire, large genomes. For model organisms and human you can also download the pre-indexed genomes [here](https://gear.embl.de/data/tracy/). To run the example, you would simply download all Homo_sapiens.GRCh37.dna.primary_assembly.fa* files and then:

`dicey search -c 45 -l 1000 -g Homo_sapiens.GRCh37.dna.primary_assembly.fa.gz -i /media/bioadmin/24e12c01-7941-49f5-9647-eeebabd15082/packages/dicey/src/primer3_config/ primers.fa`

The config directory also needs a '/' at the end.

**Comment by AlexGaithuma** [comment]
Thanks.
I had ran the indexing but no index file was generated.
The problem was fixed by compressing the reference fasta file to .gz format.

Now everything works

**Comment by AlexGaithuma** [comment]
I still get the error 

    Error opening params file
even with the indexing

**Comment by tobiasrausch** [comment]
Have you added the slash '/' at the end of the directory? Can you post the command?

**Comment by AlexGaithuma** [comment]
Thanks.
It now works.
